# Base image
FROM node:18

# Create app directory
WORKDIR /usr/src/app

# Copy package.json and yarn.lock
COPY package.json yarn.lock ./

# Install only the required dependencies (ignore dev dependencies)
# and clean yarn cache to reduce image size
RUN yarn install --production && yarn cache clean

# Bundle app source
COPY . .

# Creates a "dist" folder with the production build
RUN yarn build

# Start the server using the production build
CMD [ "yarn", "start:prod" ]
